services:
  - type: web
    name: volleyconnect-app
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    buildCommand: ""
    startCommand: "npm start"
    envVars:
      - key: DB_HOST
        value: volleyconnect-db
      - key: DB_USER
        value: app_user
      - key: DB_PASSWORD
        value: app_password
      - key: DB_NAME
        value: volleyconnect
      - key: FLUENTD_HOST
        value: volleyconnect-logs
      - key: FLUENTD_PORT
        value: "24224"
    ports:
      - port: 3000
    dependsOn:
      - volleyconnect-db
      - volleyconnect-logs

  - type: database
    name: volleyconnect-db
    env: docker
    plan: free
    image: mariadb:10.9
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        value: rootpassword
      - key: MYSQL_DATABASE
        value: volleyconnect
      - key: MYSQL_USER
        value: app_user
      - key: MYSQL_PASSWORD
        value: app_password
    ports:
      - port: 3306
    volumes:
      - name: db_data
        path: /var/lib/mysql

  - type: web
    name: volleyconnect-logs
    env: docker
    plan: free
    image: fluent/fluentd:v1.17-debian-1
    ports:
      - port: 24224
        protocol: tcp
      - port: 24224
        protocol: udp
    volumes:
      - name: fluentd_config
        path: /fluentd/etc/fluent.conf
      - name: fluentd_logs
        path: /fluentd/logs

volumes:
  - name: db_data
  - name: fluentd_config
  - name: fluentd_logs