services:
  - type: web
    name: volleyconnect-app
    runtime: docker
    region: frankfurt
    plan: free
    dockerfilePath: Dockerfile
    buildCommand: ""
    startCommand: "npm start"
    envVars:
      - key: DB_HOST
        value: volleyconnect-db
      - key: DB_USER
        value: app_user
      - key: DB_PASSWORD
        value: app_password
      - key: DB_NAME
        value: volleyconnect
      - key: FLUENTD_HOST
        value: volleyconnect-logs
      - key: FLUENTD_PORT
        value: "24224"
    dependsOn:
      - volleyconnect-db
      - volleyconnect-logs

  - type: web
    name: volleyconnect-db
    env: docker
    plan: free
    image: mariadb:10.9
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        value: rootpassword
      - key: MYSQL_DATABASE
        value: volleyconnect
      - key: MYSQL_USER
        value: app_user
      - key: MYSQL_PASSWORD
        value: app_password

  - type: web
    name: volleyconnect-logs
    env: docker
    plan: free
    image: fluent/fluentd:v1.17-debian-1